### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#13]
*Not used to GitHub 'Issues' - Will mal ausprobieren, wie das mit den Issues geht ...*

File **ObjektShader/DancyTreeDoodle3D.fuse**

I think there is a small bug in `float2 f2_multi_mat2(float2 A, mat2 B)' - imho it should be:

      C.x = A.x * B.r0.x + A.y * B.r1.x;  
      C.y = A.x * B.r0.y + A.y * B.r1.y;  

*... aber ich vermute, daß man in so einem Fall einfach die Korrektur vornimmt und sie vom anderen per 'pull request' begutachten lässt.*

**Comment by J-i-P-i** [comment]
Habe es gereviewt - und verstehe manchmal auch nicht die veschlungenen Pfade der Matrizenmultiplikation - Ich habe einfach beide Varianten und nehme die, die funktioniert :-)
