### ISSUE TITLE
Favela does not compile on Cuda

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#15]
Let me tackle the OpenCL issue first to prepare the code as much as possible. But as I don't have a Nvidia GPU I could then deserve some support in this regard.

Resolving Issue [Issue#14](https://github.com/nmbr73/Shadertoys/issues/14#issue-809193917) is a prerequisite for this Issue ❗

**Comment by J-i-P-i** [comment]
It is done - favela runs on Cuda - learned a lot again
