### ISSUE TITLE
New Release: Square Two

### ISSUE THREAD

**Issue by J-i-P-i** [nmbr73/Shadertoys#17]
Ich will auch mal ein Issue starten:

Vorbereitung release Square Two:

Fuses
TNTHTW.fuse
Favela.fuse
Noisecube.fuse
LonelyVoxel.fuse
CrackerCars.fuse

Installer bauen

Atom bauen und im WSL zum  Request geben

**Comment by J-i-P-i** [comment]
Hab gerade gesehen, dass dafür wahrscheinlich die Actions besser geeignet wären

**Comment by nmbr73** [comment]
Ja, aber die müsste man auch erst mal 'scripten' - insbesondere kann man's dann nicht über ein Lua-Script machen, daß in Fusion läuft. Aber bei Gelegenheit muß ich mich dringend noch mal um das Thema "Release erstellen" kümmern ... hat sich ja doch ein bisschen was getan seit unserer v0.1-aplha.1 

👋 😆👍

**Comment by nmbr73** [comment]
Ich schließe mal dieses Issue ... ist schon ein wenig veraltet (und nie erledigt) .. ich mache ein neues für unser "Reactor Release"
