### ISSUE TITLE
First attempt to create an Atom style package 

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#33]
Hi JiPi,

könntest du mal in das `Atom/`-Verzeichnis reingucken und mir sagen, was da noch falsch ist / an welcher Stelle ich da Änderungen vornehmen sollte. Ist so noch nicht zu gebrauchen, aber halt mal ein erster Wurf, den man vielleicht ausbauen kann.

Gruß und Dank und bis dahin
nmbr73

**Comment by J-i-P-i** [comment]
Hi nmbr73,

wir haben ja im Chat ja ein Schlachtplan zusammengezimmert und ich fasse es hier kurz zusammen: Die Shadertoys bekommen im Reactor die Kategorie "Shaders" - Du hattest ja so eine tolle Tabelle gemacht - Für die Dateinamen werden die Shadertoys IDs verwendet. Die Dateien bekommt im Normalfall sowieso keiner mehr zu Gesicht und es verführt auch nicht zum Editieren.


![Übersicht_Shadertoyfuses](https://user-images.githubusercontent.com/78935215/114764892-c86fe980-9d64-11eb-8cab-f5444c7971ae.png)

**Comment by nmbr73** [comment]
Ja, perfekt - habe mal das Zusammenstellen der Fuses für den Reactor etwas "restriktiver" gemacht ... damit bleiben momentan nur ein paar - weitere sollten sich aber ja einfach per Copy&Paster der betreffenden Codeblöcke reinnehmen lassen ... und dann wär's vielleicht mal an der Zeit ein Release zu basteln und das für den Reactor vorzuschlagen :-)
