### ISSUE TITLE
Some Fuses do not work on macOS/Metal

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#34]
The following Fuses currently do not work on macOS/Metal:

* <del>Abstract/OtherWorlds</del>
* <del>Blob/TorturedBlob</del>
* <del>Misc/TruePinBallPhysics</del>
* <del>Object/HW3Swing</del>
* <del>Object/WalkingCubes</del>
* <del>Tunnel/WindingMengerTunnel</del>

**Comment by tocan** [comment]
Thanks for the Info.

nmbr73 ***@***.***> schrieb am Sa., 22. Mai 2021, 20:50:

**Comment by nmbr73** [comment]
Note: For 'WindingMengerTunnel' we should solve issue #35 first.

**Comment by J-i-P-i** [comment]
With the exception of the WindingMenger, global variables are probably the cause for all fuses. Something is missing

#if defined (DEVICE_IS_METAL)
    #define inout thread
    #define out thread
#else
    #define inout
    #define out
#endif

**Comment by nmbr73** [comment]
Resolved by  [c9a8f67](https://github.com/nmbr73/Shadertoys/commit/c9a8f67e0d025100ffe80b3ab5ae3b47cdc7d991). OtherWorlds runs, but lead to an unexpected render -> #38
