### ISSUE TITLE
Some Fuses do not work on Windows/OpenCL

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#35]
The following Fuses currently do not work on Windows/OpenCL:

* <del>Misc/IHeartFourier</del>
* <del>Tunnel/WindingMengerTunnel</del>

Interestingly, the IHeartFourier works on macOS/OpenCL.
The WindingMenger causes problems on macOS not only with OpenCL, but also with Metal!

**Comment by J-i-P-i** [comment]
I Found a solution for Misc/IHeartFourier - checked in - but we have to test ist under Mac

**Comment by nmbr73** [comment]
Done :-)
